openapi: 3.0.4
info:
  title: Spam Detector
  description: Spam Detector is a simple tool for detecting spam in a text. It utilize an email address or IP address to validate the given text against the spam database.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/spamdetector:
    post:
      summary: Detect Spam
      description: Spam Detector is a simple tool for detecting spam in a text. It utilize an email address or IP address to validate the given text against the spam database.
      operationId: spamdetector
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  likelySpam: true
                  isDisposableEmail: false
                  isIPBlacklisted: false
                  ipDetails:
                    country: IN
                    region: DL
                  parsed: true
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to detect spam in
                  example: Can you please spare some change?! Desperate!!! Send cash
                email:
                  type: string
                  description: The email address to validate against the spam database. This is optional
                  example: bankers@fre.323hotlain.net
                ip:
                  type: string
                  description: The IP address to validate against the spam database.  This is optional
                  example: 122.180.184.182
              required:
              - text
              example:
                text: Can you please spare some change?! Desperate!!! Send cash
                email: bankers@fre.323hotlain.net
                ip: 122.180.184.182
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
